name: Unit tests

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  release:
    types: [ published ]

jobs:
  run-unittests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: [ '3.7', '3.8', '3.9', '3.10' ]
    name: ${{ matrix.os }}-Python-${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r test-requirements.txt
          pip install coveralls

      - name: Run Unit tests
        run: |
          pytest --cov=stf_client

      - name: coveralls
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.10'
        run: coveralls

      - name: make packages
        if: github.event_name == 'release' && matrix.os == 'ubuntu-latest' && matrix.python-version == '3.10'
        run: |
          python setup.py sdist
          python setup.py bdist_wheel

      - name: publish
        if: github.event_name == 'release' && matrix.os == 'ubuntu-latest' && matrix.python-version == '3.10'
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        run: |
          pip install twine
          export PATH=$HOME/.local/bin:$PATH
          twine upload dist/*
